In [2]:
import pandas as pd

In [4]:
# reading the csv file
df_exams = pd.read_csv("../data/StudentsPerformance.csv")
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

# Selecting one column

## Syntax 1

In [5]:
# select a column with [] (prefered way to select a column)
df_exams['gender']

0      female
1      female
2      female
3        male
4        male
        ...
995    female
996      male
997    female
998    female
999    female
Name: gender, Length: 1000, dtype: object

In [6]:
# check out the data type of a column
type(df_exams['gender'])

pandas.core.series.Series

In [9]:
# series: attributes and methods
df_exams['gender'].index
df_exams['gender'].head()

0    female
1    female
2    female
3      male
4      male
Name: gender, dtype: object

## Syntax 2

In [10]:
# select a column with .
df_exams.gender

0      female
1      female
2      female
3        male
4        male
        ...
995    female
996      male
997    female
998    female
999    female
Name: gender, Length: 1000, dtype: object

In [12]:
# select a column with . (pitfalls)
df_exams.math score

SyntaxError: invalid syntax (3061062658.py, line 2)

In [14]:
# select the same column using
df_exams['math score']

0      72
1      69
2      90
3      47
4      76
       ..
995    88
996    62
997    59
998    68
999    77
Name: math score, Length: 1000, dtype: int64

# Selecting two or more columns

In [15]:
# select 2 columns using [[]]
df_exams[['gender', 'math score']]

     gender  math score
0    female          72
1    female          69
2    female          90
3      male          47
4      male          76
..      ...         ...
995  female          88
996    male          62
997  female          59
998  female          68
999  female          77

[1000 rows x 2 columns]

In [16]:
# check out the data type of the selection
type(df_exams[['gender', 'math score']])

pandas.core.frame.DataFrame

In [19]:
# select 2 or more columns using [[]]
df_exams[['gender', 'writing score', 'math score', 'reading score']]

     gender  writing score  math score  reading score
0    female             74          72             72
1    female             88          69             90
2    female             93          90             95
3      male             44          47             57
4      male             75          76             78
..      ...            ...         ...            ...
995  female             95          88             99
996    male             55          62             55
997  female             65          59             71
998  female             77          68             78
999  female             86          77             86

[1000 rows x 4 columns]

In [20]:
# we can't select 2 or more columns with the "."
df_exams.'gender', 'math score'

SyntaxError: invalid syntax (636409209.py, line 2)