In [2]:
import pandas as pd

In [4]:
# reading the csv file
df_exams = pd.read_csv("../data/StudentsPerformance.csv")
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

# Math Operations

## Operations in columns

In [8]:
# select a column and calculate total sum
df_exams['math score'].sum()

np.int64(66089)

In [14]:
# count, mean, std, max and min
df_exams['math score'].count()
df_exams['math score'].mean()
df_exams['math score'].std()
df_exams['math score'].max()
df_exams['math score'].min()

np.int64(0)

In [16]:
# easier calculation with .describe()
df_exams.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

## Operations in rows

In [17]:
# calculating the sum in a row
df_exams['math score'] + df_exams['reading score'] + df_exams['writing score']

0      218
1      247
2      278
3      148
4      229
      ...
995    282
996    172
997    195
998    223
999    249
Length: 1000, dtype: int64

In [20]:
# calculating the average score and assigning the result to a new column
df_exams['average'] = (df_exams['math score'] + df_exams['reading score'] + df_exams['writing score'])/3

In [22]:
# showing the dataframe
df_exams.round(2)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,average
0,female,group B,bachelor's degree,standard,none,72,72,74,72.67
1,female,group C,some college,standard,completed,69,90,88,82.33
2,female,group B,master's degree,standard,none,90,95,93,92.67
3,male,group A,associate's degree,free/reduced,none,47,57,44,49.33
4,male,group C,some college,standard,none,76,78,75,76.33
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,94.00
996,male,group C,high school,free/reduced,none,62,55,55,57.33
997,female,group C,high school,free/reduced,completed,59,71,65,65.00
998,female,group D,some college,standard,completed,68,78,77,74.33
999,female,group D,some college,free/reduced,none,77,86,86,83.00

In [24]:
df_exams['average'].max()

np.float64(100.0)

# Value Counts

In [27]:
# counting gender elements

# len function
len(df_exams['gender'])
# .count() method
df_exams['gender'].count()

np.int64(1000)

In [28]:
# counting gender elements by category
df_exams['gender'].value_counts()

gender
female    518
male      482
Name: count, dtype: int64

In [30]:
# return the relative frequency (divide all values by the sum of values)
df_exams['gender'].value_counts(normalize=True)

gender
female    0.518
male      0.482
Name: proportion, dtype: float64

In [33]:
# counting "parental level of education" elements by category
df_exams['parental level of education'].value_counts()

parental level of education
some college          226
associate's degree    222
high school           196
some high school      179
bachelor's degree     118
master's degree        59
Name: count, dtype: int64

In [35]:
# return the relative frequency and round to 2 decimals
df_exams['parental level of education'].value_counts(normalize=True).round(2)

parental level of education
some college          0.23
associate's degree    0.22
high school           0.20
some high school      0.18
bachelor's degree     0.12
master's degree       0.06
Name: proportion, dtype: float64

# Sort a DataFrame

In [39]:
# sort by one column
df_exams.sort_values('average')

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,average
59,female,group C,some high school,free/reduced,none,0,17,10,9.000000
980,female,group B,high school,free/reduced,none,8,24,23,18.333333
596,male,group B,high school,free/reduced,none,30,24,15,23.000000
327,male,group A,some college,free/reduced,none,28,23,19,23.333333
17,female,group B,some high school,free/reduced,none,18,32,28,26.000000
...,...,...,...,...,...,...,...,...,...
712,female,group D,some college,standard,none,98,100,99,99.000000
114,female,group E,bachelor's degree,standard,completed,99,100,100,99.666667
962,female,group E,associate's degree,standard,none,100,100,100,100.000000
916,male,group E,bachelor's degree,standard,completed,100,100,100,100.000000
458,female,group E,bachelor's degree,standard,none,100,100,100,100.000000

In [41]:
# sort descending by one column
df_exams.sort_values('average', ascending=False)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,average
916,male,group E,bachelor's degree,standard,completed,100,100,100,100.000000
962,female,group E,associate's degree,standard,none,100,100,100,100.000000
458,female,group E,bachelor's degree,standard,none,100,100,100,100.000000
114,female,group E,bachelor's degree,standard,completed,99,100,100,99.666667
712,female,group D,some college,standard,none,98,100,99,99.000000
...,...,...,...,...,...,...,...,...,...
17,female,group B,some high school,free/reduced,none,18,32,28,26.000000
327,male,group A,some college,free/reduced,none,28,23,19,23.333333
596,male,group B,high school,free/reduced,none,30,24,15,23.000000
980,female,group B,high school,free/reduced,none,8,24,23,18.333333
59,female,group C,some high school,free/reduced,none,0,17,10,9.000000

In [44]:
# sort descending by multiple columns
df_exams.sort_values(['math score', 'reading score'], ascending=False)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,average
149,male,group E,associate's degree,free/reduced,completed,100,100,93,97.666667
458,female,group E,bachelor's degree,standard,none,100,100,100,100.000000
916,male,group E,bachelor's degree,standard,completed,100,100,100,100.000000
962,female,group E,associate's degree,standard,none,100,100,100,100.000000
625,male,group D,some college,standard,completed,100,97,99,98.666667
...,...,...,...,...,...,...,...,...,...
145,female,group C,some college,free/reduced,none,22,39,33,31.333333
787,female,group B,some college,standard,none,19,38,32,29.666667
17,female,group B,some high school,free/reduced,none,18,32,28,26.000000
980,female,group B,high school,free/reduced,none,8,24,23,18.333333
59,female,group C,some high school,free/reduced,none,0,17,10,9.000000

In [45]:
# sort descending by multiple columns and update dataframe
df_exams.sort_values(['math score', 'reading score'], ascending=False, inplace=True)

In [46]:
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,average
149,male,group E,associate's degree,free/reduced,completed,100,100,93,97.666667
458,female,group E,bachelor's degree,standard,none,100,100,100,100.000000
916,male,group E,bachelor's degree,standard,completed,100,100,100,100.000000
962,female,group E,associate's degree,standard,none,100,100,100,100.000000
625,male,group D,some college,standard,completed,100,97,99,98.666667
...,...,...,...,...,...,...,...,...,...
145,female,group C,some college,free/reduced,none,22,39,33,31.333333
787,female,group B,some college,standard,none,19,38,32,29.666667
17,female,group B,some high school,free/reduced,none,18,32,28,26.000000
980,female,group B,high school,free/reduced,none,8,24,23,18.333333
59,female,group C,some high school,free/reduced,none,0,17,10,9.000000

In [49]:
# sort descending by text column
df_exams.sort_values('race/ethnicity', ascending=True)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,average
741,female,group A,associate's degree,free/reduced,none,37,57,56,50.000000
151,male,group A,bachelor's degree,standard,none,77,67,68,70.666667
811,male,group A,high school,free/reduced,none,45,47,49,47.000000
112,male,group A,associate's degree,standard,none,54,53,47,51.333333
25,male,group A,master's degree,free/reduced,none,73,74,72,73.000000
...,...,...,...,...,...,...,...,...,...
751,male,group E,some college,standard,none,68,72,65,68.333333
915,female,group E,some college,standard,none,68,70,66,68.000000
592,male,group E,bachelor's degree,standard,none,68,68,64,66.666667
479,male,group E,associate's degree,standard,none,76,71,67,71.333333
517,female,group E,some college,standard,completed,66,74,73,71.000000

In [51]:
# sort descending with a key function
df_exams.sort_values('race/ethnicity', ascending=True, key=lambda col:col.str.lower())

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,average
741,female,group A,associate's degree,free/reduced,none,37,57,56,50.000000
151,male,group A,bachelor's degree,standard,none,77,67,68,70.666667
811,male,group A,high school,free/reduced,none,45,47,49,47.000000
112,male,group A,associate's degree,standard,none,54,53,47,51.333333
25,male,group A,master's degree,free/reduced,none,73,74,72,73.000000
...,...,...,...,...,...,...,...,...,...
751,male,group E,some college,standard,none,68,72,65,68.333333
915,female,group E,some college,standard,none,68,70,66,68.000000
592,male,group E,bachelor's degree,standard,none,68,68,64,66.666667
479,male,group E,associate's degree,standard,none,76,71,67,71.333333
517,female,group E,some college,standard,completed,66,74,73,71.000000

# Create Index

In [53]:
import numpy as np
import random

In [55]:
# creating non repetative values for the index
new_index = np.arange(0, 1000)

In [57]:
# shuffling the indexes
random.shuffle(new_index)

In [60]:
# create a new column with new index
df_exams['new_index'] = new_index
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,average,new_index
149,male,group E,associate's degree,free/reduced,completed,100,100,93,97.666667,302
458,female,group E,bachelor's degree,standard,none,100,100,100,100.000000,649
916,male,group E,bachelor's degree,standard,completed,100,100,100,100.000000,222
962,female,group E,associate's degree,standard,none,100,100,100,100.000000,14
625,male,group D,some college,standard,completed,100,97,99,98.666667,393
...,...,...,...,...,...,...,...,...,...,...
145,female,group C,some college,free/reduced,none,22,39,33,31.333333,508
787,female,group B,some college,standard,none,19,38,32,29.666667,759
17,female,group B,some high school,free/reduced,none,18,32,28,26.000000,826
980,female,group B,high school,free/reduced,none,8,24,23,18.333333,679
59,female,group C,some high school,free/reduced,none,0,17,10,9.000000,599

# Set Index

In [62]:
# set new_index column as index
df_exams.set_index('new_index', inplace=True)
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,average
new_index,,,,,,,,,
302,male,group E,associate's degree,free/reduced,completed,100,100,93,97.666667
649,female,group E,bachelor's degree,standard,none,100,100,100,100.000000
222,male,group E,bachelor's degree,standard,completed,100,100,100,100.000000
14,female,group E,associate's degree,standard,none,100,100,100,100.000000
393,male,group D,some college,standard,completed,100,97,99,98.666667
...,...,...,...,...,...,...,...,...,...
508,female,group C,some college,free/reduced,none,22,39,33,31.333333
759,female,group B,some college,standard,none,19,38,32,29.666667
826,female,group B,some high school,free/reduced,none,18,32,28,26.000000
679,female,group B,high school,free/reduced,none,8,24,23,18.333333
599,female,group C,some high school,free/reduced,none,0,17,10,9.000000

# Sort Index

In [64]:
# sort dataframe by new index
df_exams.sort_index()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,average
new_index,,,,,,,,,
0,male,group B,associate's degree,free/reduced,completed,82,78,74,78.000000
1,male,group E,associate's degree,standard,completed,71,74,68,71.000000
2,male,group C,some high school,standard,none,75,72,62,69.666667
3,female,group C,some college,standard,none,58,59,66,61.000000
4,male,group A,bachelor's degree,standard,none,91,96,92,93.000000
...,...,...,...,...,...,...,...,...,...
995,female,group B,associate's degree,free/reduced,none,53,71,67,63.666667
996,female,group B,some high school,free/reduced,completed,52,67,72,63.666667
997,male,group D,some college,standard,none,88,77,77,80.666667
998,male,group D,master's degree,standard,none,95,81,84,86.666667
999,female,group C,associate's degree,free/reduced,none,60,75,74,69.666667

In [66]:
# sort descending by index
df_exams.sort_index(ascending=False, inplace=True)
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,average
new_index,,,,,,,,,
999,female,group C,associate's degree,free/reduced,none,60,75,74,69.666667
998,male,group D,master's degree,standard,none,95,81,84,86.666667
997,male,group D,some college,standard,none,88,77,77,80.666667
996,female,group B,some high school,free/reduced,completed,52,67,72,63.666667
995,female,group B,associate's degree,free/reduced,none,53,71,67,63.666667
...,...,...,...,...,...,...,...,...,...
4,male,group A,bachelor's degree,standard,none,91,96,92,93.000000
3,female,group C,some college,standard,none,58,59,66,61.000000
2,male,group C,some high school,standard,none,75,72,62,69.666667
1,male,group E,associate's degree,standard,completed,71,74,68,71.000000
0,male,group B,associate's degree,free/reduced,completed,82,78,74,78.000000